services:
  - type: web
    name: vvnewsdigestbot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: MODE
        value: RENDER
      # PORT не задаємо вручну
      # (інші секрети краще зберігати через Render Dashboard або .env)